language: R
install:
  - R -e "install.packages('rmarkdown')"
  - R -e "install.packages('csv')"

script: make && rm .gitignore

deploy:
  provider: pages
  github-token: ${github_token}
  skip-cleanup: true
  on:
    branch: master
